name: sura_work
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9.18
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - torch=2.3.0
  - torchvision=0.18.0
  - Pillow=10.3.0
  - h5py=3.9.0
  - matplotlib=3.8.4
  - py-opencv=4.10.0
